# Generated by Django 5.2.6 on 2026-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_guest',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
