# Generated by Django 5.2.6 on 2026-08-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0006_remove_cateringpackage_icon_cateringpackage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='menusection',
            options={'ordering': ['order', 'id']},
        ),
    ]
