# Generated by Django 5.2.6 on 2026-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0007_alter_menucategory_options_alter_menusection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Catering Packages', max_length=200)),
                ('hero_subtitle', models.TextField(default='Select the perfect menu for your event')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='catering_page/')),
            ],
        ),
    ]
