# Generated by Django 5.2.6 on 2026-08-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0008_cateringpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id']},
        ),
    ]
