# Generated by Django 5.2.6 on 2026-08-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0009_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['id']},
        ),
    ]
