# Generated by Django 5.2.6 on 2026-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0012_remove_stagedesign_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedesign',
            name='badge',
            field=models.CharField(blank=True, default='New!', help_text='Badge text to display on stage card (e.g. New!, Popular, Trending)', max_length=50),
        ),
    ]
