# Generated by Django 5.2.6 on 2026-08-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0014_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Premium Banquet Halls', max_length=200)),
                ('hero_subtitle', models.TextField(default='Discover the perfect venue for your weddings, receptions, and corporate celebrations.')),
                ('hero_badge', models.CharField(default='LUXURY VENUES', max_length=100)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hall_page/')),
            ],
        ),
    ]
